{% set name = "brendapy" %}
{% set version = "0.5.0" %}

package:
  name: brendapy
  version: {{ version }}

source:
  - path: ..
  - url: https://github.com/noparis/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 6483e20b0faf807212b71502e74d08ce7c2acd3e76aaff5836c5912132a45247
  # External dependencies
  - url: https://github.com/matthiaskoenig/pymetadata/archive/refs/heads/develop.zip
    sha256: 778da51351adac7aafba5f500f8148079c54a88de77c7219404a08bd0062a536
    folder: brendapy/ontologies/pymetadata

build:
  #noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.11
    - depinfo>=0.1.7
    - rich
    - requests
    - pandas>=1.4.0
    - pyparsing>=3.0.9
    - ujson>=5.2.0

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-mock
  imports:
    - brendapy
  commands:
    - python -m brendapy --help
    - pytest tests -v

about:
  home: https://github.com/matthiaskoenig/brendapy
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthiaskoenig
    - tduigou
    - noparis